image: maven:3.9.5-eclipse-temurin-17

# Pipeline Stages
stages:
  - build
  - test
  - sonar
  - deploy

# Cache Maven Dependencies
cache:
  paths:
    - .m2/repository/
    - target/

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"

# ==================== BUILD STAGE ====================
# Kompiliert den Java-Code
build:
  stage: build
  script:
    - echo "🔨 Building the application..."
    - mvn $MAVEN_CLI_OPTS clean compile
  artifacts:
    paths:
      - target/classes/
    expire_in: 1 hour

# ==================== TEST STAGE ====================
# Führt alle Unit Tests aus
unit-tests:
  stage: test
  script:
    - echo "🧪 Running unit tests..."
    - mvn $MAVEN_CLI_OPTS test
    - echo "✅ Tests completed!"
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
    paths:
      - target/surefire-reports/
      - target/jacoco.exec
    expire_in: 1 week
  coverage: '/Total.*?([0-9]{1,3})%/'

# ==================== SONAR STAGE ====================
# Analysiert Code-Qualität mit SonarCloud
sonarcloud-check:
  stage: sonar
  image: maven:3.9.5-eclipse-temurin-17
  dependencies:
    - unit-tests
  script:
    - echo "📊 Running SonarCloud analysis..."
    - mvn verify sonar:sonar
      -Dsonar.projectKey=$SONAR_PROJECT_KEY
      -Dsonar.organization=$SONAR_ORGANIZATION
      -Dsonar.host.url=https://sonarcloud.io
      -Dsonar.login=$SONAR_TOKEN
      -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
    - echo "✅ SonarCloud analysis completed!"
  only:
    - main
    - develop
    - merge_requests

# ==================== DEPLOY STAGE ====================
# Stellt Test-Reports als GitLab Pages bereit
pages:
  stage: deploy
  dependencies:
    - unit-tests
  script:
    - echo "🚀 Deploying test reports to GitLab Pages..."
    - mvn jacoco:report
    - mkdir -p public/coverage
    - mkdir -p public/test-reports
    - cp -r target/site/jacoco/* public/coverage/ || echo "No coverage reports"
    - cp -r target/surefire-reports/* public/test-reports/ || echo "No test reports"
    - |
      cat > public/index.html << 'EOF'
      <!DOCTYPE html>
      <html>
      <head>
          <title>Task Management API - Test Dashboard</title>
          <style>
              * { margin: 0; padding: 0; box-sizing: border-box; }
              body {
                  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                  min-height: 100vh;
                  padding: 40px 20px;
              }
              .container {
                  max-width: 1000px;
                  margin: 0 auto;
                  background: white;
                  border-radius: 20px;
                  box-shadow: 0 20px 60px rgba(0,0,0,0.3);
                  overflow: hidden;
              }
              .header {
                  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                  color: white;
                  padding: 40px;
                  text-align: center;
              }
              .header h1 {
                  font-size: 2.5em;
                  margin-bottom: 10px;
              }
              .header p {
                  font-size: 1.2em;
                  opacity: 0.9;
              }
              .content {
                  padding: 40px;
              }
              .card-grid {
                  display: grid;
                  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
                  gap: 20px;
                  margin-top: 30px;
              }
              .card {
                  background: #f8f9fa;
                  border-radius: 15px;
                  padding: 30px;
                  text-align: center;
                  transition: all 0.3s ease;
                  border: 2px solid transparent;
              }
              .card:hover {
                  transform: translateY(-5px);
                  box-shadow: 0 10px 30px rgba(0,0,0,0.1);
                  border-color: #667eea;
              }
              .card-icon {
                  font-size: 3em;
                  margin-bottom: 15px;
              }
              .card h3 {
                  color: #333;
                  margin-bottom: 10px;
                  font-size: 1.3em;
              }
              .card p {
                  color: #666;
                  font-size: 0.9em;
                  line-height: 1.6;
                  margin-bottom: 20px;
              }
              .card a {
                  display: inline-block;
                  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                  color: white;
                  padding: 12px 30px;
                  border-radius: 25px;
                  text-decoration: none;
                  font-weight: bold;
                  transition: all 0.3s ease;
              }
              .card a:hover {
                  transform: scale(1.05);
                  box-shadow: 0 5px 15px rgba(102, 126, 234, 0.4);
              }
              .footer {
                  text-align: center;
                  padding: 30px;
                  color: #666;
                  border-top: 1px solid #eee;
              }
              .badge {
                  display: inline-block;
                  background: #10b981;
                  color: white;
                  padding: 5px 15px;
                  border-radius: 20px;
                  font-size: 0.8em;
                  margin: 10px 0;
              }
          </style>
      </head>
      <body>
          <div class="container">
              <div class="header">
                  <h1>🚀 Task Management API</h1>
                  <p>Test Dashboard & Quality Reports</p>
                  <span class="badge">✓ Tests Passing</span>
              </div>
      
              <div class="content">
                  <div class="card-grid">
                      <div class="card">
                          <div class="card-icon">📊</div>
                          <h3>Code Coverage</h3>
                          <p>JaCoCo Analyse - Zeigt welcher Code durch Tests abgedeckt ist</p>
                          <a href="coverage/index.html">Coverage Report öffnen</a>
                      </div>
      
                      <div class="card">
                          <div class="card-icon">🧪</div>
                          <h3>Unit Tests</h3>
                          <p>Detaillierte Testergebnisse aller Unit Tests</p>
                          <a href="test-reports/">Test Reports öffnen</a>
                      </div>
      
                      <div class="card">
                          <div class="card-icon">🔍</div>
                          <h3>SonarCloud</h3>
                          <p>Code-Qualität, Bugs, Code Smells und Security Issues</p>
                          <a href="https://sonarcloud.io" target="_blank">SonarCloud Dashboard</a>
                      </div>
                  </div>
              </div>
      
              <div class="footer">
                  <p>Letzte Aktualisierung: <span id="date"></span></p>
                  <p style="margin-top: 10px; font-size: 0.9em;">
                      Modul 450 - Test Driven Development Project
                  </p>
              </div>
          </div>
          <script>
              document.getElementById('date').textContent = new Date().toLocaleString('de-CH');
          </script>
      </body>
      </html>
      EOF
    - echo "✅ Deployment completed!"
  artifacts:
    paths:
      - public
  only:
    - main
    - develop